# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-GB"
title                    : "Liam Chalcroft"
title_separator          : "-"
name                     : &name "Liam Chalcroft"
description              : &description "Founding Computer Vision Scientist at Prospectral. PhD in machine learning for medical imaging, University College London."
url                      : https://liamchalcroft.github.io
baseurl                  : ""
og_image                 : og-image.png
future                   : true   # forthcoming publications are dated to their venue
feed:
  disable_in_head: true
  collections:
    publications:
      path: /publications/feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Site Author
author:
  name             : "Liam Chalcroft"
  location         : "London"
  email            : "liamchalcroft@gmail.com"
  github           : "liamchalcroft"
  googlescholar    : "https://scholar.google.com/citations?user=u3EHJ0gAAAAJ&hl=en"
  orcid            : "https://orcid.org/0000-0003-3363-6454"
  linkedin         : "liamchalcroft"

# Reading Files
include:
  - _pages
exclude:
  - .bundle
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: Europe/London

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

compress_html:
  clippings: all
  ignore:
    envs: development
